### ISSUE TITLE
스크롤바 디자인

### ISSUE THREAD

**Issue by gschoi1224** [gschoi1224/SkillUp#7]
```css
::-webkit-scrollbar { width : 스크롤바 넓이 }
::-webkit-scrollbar-track { background-color:트랙 배경 색상 }
::-webkit-scrollbar-thumb { background-color : 바 색상, border-radius : 바 둥근 모서리 정도 }
::-webkit-scrollbar-thumb:hover { background : 마우스를 올렸을 때 색상 }
::-webkit-scrollbar-button:start:decrement, ::-webkit-scrollbar-button:end:increment {
    width : 버튼 넓이;
    height : 버튼 높이;
    background : 버튼 색상;
 }
```
